@startuml

autonumber
hide footbox
title Menolak Disposisi BKD

Actor Kepala
boundary Dashboard_V
boundary DisposisiBKD_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Disposisi BKD
Dashboard_V --> SuratDisposisi_C: disposisibkd()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Kepala: Halaman Disposisi BKD

Kepala --> DisposisiBKD_V: klik tombol tolak Disposisi BKD
DisposisiBKD_V --> SuratDisposisi_C: rejectbkd()
SuratDisposisi_C --> SuratDisposisi_E:
   
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Kepala: Halaman Disposisi BKD

@enduml