@startuml

autonumber
hide footbox
title Melihat Persetujuan SPT BKA

Actor Kepala
boundary Dashboard_V
boundary SPTBKA_V
boundary UploadSPTBKA_V
control Admin_C
control SuratPerintahTugas_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Persetujuan SPT BKA
Dashboard_V --> SuratPerintahTugas_C: sptbka()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> SPTBKA_V: load->view()
    SPTBKA_V --> Kepala: Halaman Persetujuan SPT BKA

Kepala --> SPTBKA_V: klik tombol Upload Persetujuan SPT BKA
SPTBKA_V --> SuratPerintahTugas_C: uploadsptbka()
SuratPerintahTugas_C --> UploadSPTBKA_V: load->view()
UploadSPTBKA_V --> Kepala: Halaman Upload File Persetujuan SPT BKA

Kepala --> UploadSPTBKA_V: Mengisi Inputan dan klik tombol upload
    note right of Kepala
        Inputan file SPT BKD lengkap
            end note
UploadSPTBKA_V --> SuratPerintahTugas_C: uploadsptbka()
SuratPerintahTugas_C --> SuratPerintahTugas_E:

alt isValid() case
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C: isValid()
    SuratPerintahTugas_C --> SPTBKA_V: load->view()
    SPTBKA_V --> Kepala: Halaman Persetujuan SPT BKA

else isInvalid() case
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C: isInValid()
    SuratPerintahTugas_C --> UploadSPTBKA_V: load->view()
    UploadSPTBKA_V --> Kepala: Halaman Upload SPT BKA
end
@enduml