@startuml

autonumber
hide footbox
title Mengupload Persetujuan Disposisi BKD

Actor Kepala
boundary Dashboard_V
boundary DisposisiBKD_V
boundary UploadDisposisiBKD_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Disposisi BKD
Dashboard_V --> SuratDisposisi_C: disposisibkd()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Kepala: Halaman Disposisi BKD

Kepala --> DisposisiBKD_V: klik tombol Upload Disposisi BKD
DisposisiBKD_V --> SuratDisposisi_C: uploaddisposisibkd()
SuratDisposisi_C --> UploadDisposisiBKD_V: load->view()
UploadDisposisiBKD_V --> Kepala: Halaman Upload File Persetujuan Disposisi BKD

Kepala --> UploadDisposisiBKD_V: Mengisi Inputan dan klik tombol upload
    note right of Kepala
        Inputan file Disposisi BKD lengkap
            end note
UploadDisposisiBKD_V --> SuratDisposisi_C: uploaddisposisibkd()
SuratDisposisi_C --> SuratDisposisi_E:

alt isValid() case
    
    SuratDisposisi_E --> SuratDisposisi_C: isValid()
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Kepala: Halaman Disposisi BKD

else isInvalid() case
    
    SuratDisposisi_E --> SuratDisposisi_C: isValid()
    SuratDisposisi_C --> UploadDisposisiBKD_V: load->view()
    UploadDisposisiBKD_V --> Kepala: Halaman Upload Disposisi BKD

end
@enduml