@startuml

autonumber
hide footbox
title Mengupload Persetujuan SPT BKD

Actor Kepala
boundary Dashboard_V
boundary SPTBKD_V
boundary UploadSPTBKD_V
control Admin_C
control SuratPerintahTugas_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Persetujuan SPT BKD
Dashboard_V --> SuratPerintahTugas_C: index()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> SPTBKD_V: load->view()
    SPTBKD_V --> Kepala: Halaman Persetujuan SPT BKD

Kepala --> SPTBKD_V: klik tombol Upload Persetujuan SPT BKD
SPTBKD_V --> SuratPerintahTugas_C: uploadsptbkd()
SuratPerintahTugas_C --> UploadSPTBKD_V: load->view()
UploadSPTBKD_V --> Kepala: Halaman Upload File Persetujuan SPT BKD

Kepala --> UploadSPTBKD_V: Mengisi Inputan dan klik tombol upload
    note right of Kepala
        Inputan file SPT BKD lengkap
            end note
UploadSPTBKD_V --> SuratPerintahTugas_C: uploadsptbkd()
SuratPerintahTugas_C --> SuratPerintahTugas_E:

alt isValid() case
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C: isValid()
    SuratPerintahTugas_C --> SPTBKD_V: load->view()
    SPTBKD_V --> Kepala: Halaman Persetujuan SPT BKD

else isInvalid() case
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C: isInValid()
    SuratPerintahTugas_C --> UploadSPTBKD_V: load->view()
    UploadSPTBKD_V --> Kepala: Halaman Upload SPT BKD

end
@enduml