@startuml

autonumber
hide footbox
title Melihat File Disposisi BKA

Actor Kepala
boundary Dashboard_V
boundary DisposisiBKA_V
boundary PDF_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Disposisi BKA
Dashboard_V --> SuratDisposisi_C: disposisibka()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKA_V: load->view()
    DisposisiBKA_V --> Kepala: Halaman Disposisi BKA

Kepala --> DisposisiBKA_V: klik tombol Lihat File Disposisi BKA
DisposisiBKA_V --> SuratDisposisi_C: viewdisposisimail()
SuratDisposisi_C --> SuratDisposisi_E:
   
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> PDF_V: load->view()
    PDF_V --> Kepala: Tampilan file Disposisi BKA

@enduml