@startuml

autonumber
hide footbox
title Melihat Persetujuan Disposisi 

Actor Kepala
boundary Dashboard_V
boundary PersetujuanDisposisi_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Kepala: Halaman Dashboard
Kepala --> Dashboard_V: klik menu Persetujuan Disposisi 
Dashboard_V --> SuratDisposisi_C: index()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> PersetujuanDisposisi_V: load->view()
    PersetujuanDisposisi_V --> Kepala: Halaman Persetujuan Disposisi 

@enduml