@startuml

autonumber
hide footbox
title Lihat File SPT BKD

Actor Aktor_AdminTU
boundary Dashboard_V
boundary KontrolSPTBKD_V
boundary PDF_V
control Admin_C
control KontrolSPT_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_AdminTU: Halaman Dashboard
Aktor_AdminTU --> Dashboard_V: klik menu SPT BKD
Dashboard_V --> KontrolSPT_C: index()
KontrolSPT_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> KontrolSPTBKD_V: load->view()
    KontrolSPTBKD_V --> Aktor_AdminTU: Halaman SPT BKD

Aktor_AdminTU --> KontrolSPTBKD_V: klik tombol Lihat File SPT BKD
KontrolSPTBKD_V --> KontrolSPT_C: viewspt()
KontrolSPT_C --> SuratPerintahTugas_E:
   
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> PDF_V: load->view()
    PDF_V --> Aktor_AdminTU: Tampilan file SPT

@enduml