@startuml

autonumber
hide footbox
title Lihat Persetujuan SPT BKD 

Actor Aktor_Kepala
boundary Dashboard_V
boundary SPTBKD_V
control Admin_C
control SuratPerintahTugas_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Kepala: Halaman Dashboard
Aktor_Kepala --> Dashboard_V: klik menu Persetujuan SPT BKD 
Dashboard_V --> SuratPerintahTugas_C: sptbka()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> SPTBKD_V: load->view()
    SPTBKD_V --> Aktor_Kepala: Halaman Persetujuan SPT BKD 

@enduml