@startuml

autonumber
hide footbox
title Lihat File Persetujuan Disposisi BKD

Actor Aktor_Kepala
boundary Dashboard_V
boundary DisposisiBKD_V
boundary PDF_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Kepala: Halaman Dashboard
Aktor_Kepala --> Dashboard_V: klik menu Disposisi BKD
Dashboard_V --> SuratDisposisi_C: disposisibkd()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Aktor_Kepala: Halaman Disposisi BKD

Aktor_Kepala --> DisposisiBKD_V: klik tombol Lihat File Persetujuan Disposisi BKD
DisposisiBKD_V --> SuratDisposisi_C: viewpersetujuandisposisi()
SuratDisposisi_C --> SuratDisposisi_E:
   
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> PDF_V: load->view()
    PDF_V --> Aktor_Kepala: Tampilan file Persetujuan Disposisi BKD

@enduml