@startuml

autonumber
hide footbox
title Lihat File Persetujuan SPT BKA

Actor Aktor_Kepala
boundary Dashboard_V
boundary SPRBKA_V
boundary PDF_V
control Admin_C
control SuratPerintahTugas_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Kepala: Halaman Dashboard
Aktor_Kepala --> Dashboard_V: klik menu SPT BKA
Dashboard_V --> SuratPerintahTugas_C: sptbka()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> SPRBKA_V: load->view()
    SPRBKA_V --> Aktor_Kepala: Halaman SPT BKA

Aktor_Kepala --> SPRBKA_V: klik tombol Lihat File Persetujuan SPT BKA
SPRBKA_V --> SuratPerintahTugas_C: viewspt()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
   
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> PDF_V: load->view()
    PDF_V --> Aktor_Kepala: Tampilan file Persetujuan SPT BKA

@enduml