@startuml

autonumber
hide footbox
title Lihat File Persetujuan Disposisi BKA

Actor Aktor_AdminBKA
boundary Dashboard_V
boundary SuratBKA_V
boundary PDF_V
control Admin_C
control BKA_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_AdminBKA: Halaman Dashboard
Aktor_AdminBKA --> Dashboard_V: klik menu Surat BKA
Dashboard_V --> BKA_C: index()
BKA_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> BKA_C:
    BKA_C --> SuratBKA_V: load->view()
    SuratBKA_V --> Aktor_AdminBKA: Halaman Surat BKA

Aktor_AdminBKA --> SuratBKA_V: klik tombol Lihat Persetujuan disposisi
SuratBKA_V --> BKA_C: viewpersetujuandisposisi()
BKA_C --> SuratDisposisi_E:
   
    SuratDisposisi_E --> BKA_C:
    BKA_C --> PDF_V: load->view()
    PDF_V --> Aktor_AdminBKA: Tampilan Persetujuan Disposisi

@enduml