@startuml

autonumber
hide footbox
title editprofil Aktor

Actor Aktor
boundary dashboard
boundary changepassword
control User
Entity user

User --> dashboard: load->view()
dashboard --> Aktor: Halaman dashboard
Aktor --> dashboard: klik menu changepassword
dashboard --> User: changepassword()
User --> user:
    
    user --> User:
    User --> changepassword: load->view()
    changepassword --> Aktor: Halaman change password

Aktor --> changepassword: Mengisi Inputan
    note right of Aktor
        Inputan current password, new password dan repeat password
            end note
changepassword --> User: changepassword()
User --> user:

alt isValid() case
    
    user --> User: isValid()
    User --> changepassword: load->view()
    changepassword --> Aktor: Halaman changepassword

else isInvalid() case
    
    user --> User: isInvalid()
    User --> changepassword: load->view()
    changepassword --> Aktor: this field is required
end

@enduml