@startuml

autonumber
hide footbox
title myprofil Aktor

Actor Aktor
boundary Dashboard_V
boundary MyProfile_V
control User_C
Entity User_E

User_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor: Halaman Dashboard_V
Aktor --> Dashboard_V: klik menu my profil
Dashboard_V --> User_C: index()
User_C --> User_E:
    
    User_E --> User_C:
    User_C --> MyProfile_V: load->view()
    MyProfile_V --> Aktor: Halaman my profil

@enduml