@startuml

autonumber
hide footbox
title Mencari Menu

Actor Admin
boundary Dashborad_V
boundary Menu_V
control Admin_C
control Menu_C
Entity Menu_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Admin: Halaman Dashborad
Admin --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> Menu_C: searchmenu()
Menu_C --> Menu_E:
    
    Menu_E --> Menu_C:
    Menu_C --> Menu_V: load->view()
    Menu_V --> Admin: Halaman Menu management

@enduml