@startuml

autonumber
hide footbox
title Mencari Pegawai TU

Actor Admin
boundary Dashborad_V
boundary PegawaiTU_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Admin: Halaman Dashborad
Admin --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> Pegawai_C: searchpegawaitu()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Admin: Halaman Pegawai TU

@enduml