@startuml

autonumber
hide footbox
title Mencari Surat Perintah Tugas

Actor Aktor_AdminBKD
boundary Dashborad_V
boundary SuratPerintahTugas_V
control Admin_C
control BKD_C
Entity SuratPerintahTugas_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Aktor_AdminBKD: Halaman Dashborad
Aktor_AdminBKD --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> BKD_C: searchspt()
BKD_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> BKD_C:
    BKD_C --> SuratPerintahTugas_V: load->view()
    SuratPerintahTugas_V --> Aktor_AdminBKD: Halaman Surat Perintah Tugas

@enduml