@startuml

autonumber
hide footbox
title Mencari SPT BKD

Actor Aktor_AdminTU
boundary Dashborad_V
boundary SPTBKD_V
control Admin_C
control KontrolSPT_C
Entity SuratPerintahTugas_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Aktor_AdminTU: Halaman Dashborad
Aktor_AdminTU --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> KontrolSPT_C: searchkontrolsptbkd()
KontrolSPT_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> SPTBKD_V: load->view()
    SPTBKD_V --> Aktor_AdminTU: Halaman SPT BKD

@enduml