@startuml

autonumber
hide footbox
title Forgot Password Aktor

Actor Aktor
boundary Login_V
boundary ForgotPassword_V
control Auth_C
Entity User_E

Auth_C --> Login_V: load->view()
Login_V --> Aktor: Halaman Login

Aktor --> Login_V: klik forgot password
Login_V --> Auth_C: forgotpassword()
Auth_C --> ForgotPassword_V: load->view()
ForgotPassword_V --> Aktor: Halaman Dashboard

Aktor --> ForgotPassword_V: Mengisi Inputan
    note right of Aktor
        Inputan email
            end note
ForgotPassword_V --> Auth_C: forgotpassword()
Auth_C --> User_E:

alt isValid() case
    
    User_E --> Auth_C: isValid()
    Auth_C --> ForgotPassword_V: load->view()
    ForgotPassword_V --> Aktor: Halaman Forgot Password

else isInvalid() case
    
    User_E --> Auth_C: isInvalid()
    Auth_C --> ForgotPassword_V: load->view()
    ForgotPassword_V --> Aktor: Halaman Forgot Password

end

@enduml