@startuml

autonumber
hide footbox
title Mencari Surat BKD

Actor AdministratorBKA
boundary Dashborad_V
boundary SuratBKD_V
control Admin_C
control BKD_C
Entity SuratDisposisi_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> AdministratorBKA: Halaman Dashborad
AdministratorBKA --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> BKD_C: searchbkd()
BKD_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> BKD_C:
    BKD_C --> SuratBKD_V: load->view()
    SuratBKD_V --> AdministratorBKA: Halaman Surat BKD

@enduml