@startuml

autonumber
hide footbox
title Tambah Pegawai BKA

Actor Aktor_Admin
boundary Dashboard_V
boundary PegawaiBKA_V
boundary AddPegawaiBKA_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Admin: Halaman Dashboard
Aktor_Admin --> Dashboard_V: klik menu Pegawai BKA
Dashboard_V --> Pegawai_C: pegawaibka()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiBKA_V: load->view()
    PegawaiBKA_V --> Aktor_Admin: Halaman Pegawai BKA

Aktor_Admin --> PegawaiBKA_V: klik tombol Add Pegawai TA
PegawaiBKA_V --> Pegawai_C: addpegawaibka()
Pegawai_C --> AddPegawaiBKA_V: load->view()
AddPegawaiBKA_V --> Aktor_Admin: Halaman Add Pegawai BKA

Aktor_Admin --> AddPegawaiBKA_V: Mengisi Inputan dan klik tombol add
    note right of Aktor_Admin
        Inputan Nama, NIP, Jenis Kelamin, tempat lahir, tanggal lahir, alamat dan jabatan
            end note
AddPegawaiBKA_V --> Pegawai_C: addpegawaibka()
Pegawai_C --> Pegawai_E:

alt isValid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> PegawaiBKA_V: load->view()
    PegawaiBKA_V --> Aktor_Admin: Halaman Pegawai BKA

else isInvalid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> AddPegawaiBKA_V: load->view()
    AddPegawaiBKA_V --> Aktor_Admin: Halaman Add Pegawai BKA

end
@enduml