@startuml

autonumber
hide footbox
title hapus Submenu

Actor Aktor_Admin
boundary Dashboard_V
boundary Submenu_V
control Admin_C
control Menu_C
Entity Submenu_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Admin: Halaman Dashboard
Aktor_Admin --> Dashboard_V: klik Submenu Submenu management
Dashboard_V --> Menu_C: Submenu()
Menu_C --> Submenu_E:
    
    Submenu_E --> Menu_C:
    Menu_C --> Submenu_V: load->view()
    Submenu_V --> Aktor_Admin: Halaman Submenu management

Aktor_Admin --> Submenu_V: klik tombol deletesubmenu
Submenu_V --> Menu_C: deletesubmenu()
Menu_C --> Submenu_E:
  
    Submenu_E --> Menu_C:
    Menu_C --> Submenu_V: load->view()
    Submenu_V --> Aktor_Admin: Halaman Submenu

@enduml