@startuml

autonumber
hide footbox
title Melihat File Persetujuan Disposisi BKA

Actor AdminBKA
boundary Dashboard_V
boundary SuratBKA_V
boundary PDF_V
control Admin_C
control BKA_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdminBKA: Halaman Dashboard
AdminBKA --> Dashboard_V: klik menu Surat BKA
Dashboard_V --> BKA_C: index()
BKA_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> BKA_C:
    BKA_C --> SuratBKA_V: load->view()
    SuratBKA_V --> AdminBKA: Halaman Surat BKA

AdminBKA --> SuratBKA_V: klik tombol Lihat Persetujuan disposisi
SuratBKA_V --> BKA_C: viewpersetujuandisposisi()
BKA_C --> SuratDisposisi_E:
   
    SuratDisposisi_E --> BKA_C:
    BKA_C --> PDF_V: load->view()
    PDF_V --> AdminBKA: Tampilan Persetujuan Disposisi

@enduml