@startuml

autonumber
hide footbox
title Login Aktor

Actor Aktor
boundary Login
boundary Dashboard
control Auth
Entity User

Auth --> Login: load->view()
Login --> Aktor: Halaman Login
Aktor --> Login: Mengisi Inputan
    note right of Aktor
        Inputan email dan password
            end note
Login --> Auth: index()
Auth --> User:

alt isValid() case
    
    User --> Auth: isValid()
    Auth --> Dashboard: load->view()
    Dashboard --> Aktor: Halaman Dashboard

else isInvalid() case
    
    User --> Auth: isInvalid()
    Auth --> Login: load->view()
    Login --> Aktor: email not registered/ wrong password

end

@enduml