@startuml

autonumber
hide footbox
title editprofil Aktor

Actor Aktor
boundary Dashboard_V
boundary ChangePassword_V
control User_C
Entity User_E

User_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor: Halaman Dashboard
Aktor --> Dashboard_V: klik menu ChangePassword
Dashboard_V --> User_C: ChangePassword()
User_C --> User_E:
    
    User_E --> User_C:
    User_C --> ChangePassword_V: load->view()
    ChangePassword_V --> Aktor: Halaman change password

Aktor --> ChangePassword_V: Mengisi Inputan
    note right of Aktor
        Inputan current password, new password dan repeat password
            end note
ChangePassword_V --> User_C: ChangePassword()
User_C --> User_E:

alt isValid() case
    
    User_E --> User_C: isValid()
    User_C --> ChangePassword_V: load->view()
    ChangePassword_V --> Aktor: Halaman ChangePassword

else isInvalid() case
    
    User_E --> User_C: isInvalid()
    User_C --> ChangePassword_V: load->view()
    ChangePassword_V --> Aktor: this field is required
end

@enduml