@startuml

autonumber
hide footbox
title Pemberitahuan Surat BKA

Actor AdminBKA
boundary Dashborad_V
boundary SuratBKA_V
control Admin_C
control BKA_C
Entity SuratDisposisi_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> AdminBKA: Halaman Dashborad
AdminBKA --> Dashborad_V: klik tombol pemberitahuan
Dashborad_V --> BKA_C: index()
BKA_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> BKA_C:
    BKA_C --> SuratBKA_V: load->view()
    SuratBKA_V --> AdminBKA: Halaman Surat BKA

@enduml