@startuml UsecaseMSPT
Left to Right Direction
skinParam packageStyle rectangle

actor Admin_BKA

rectangle "Use Case Diagram Manajemen Surat Perintah Tugas"{


    Admin_BKA -- (Melihat Dashboard)
    Admin_BKA -- (Melihat Profil)
    Admin_BKA -- (Mengubah Profil)
    Admin_BKA-- (Mengubah Password)
    Admin_BKA -- (Forgot Password)
    Admin_BKA -- (Melihat Surat BKA)
    Admin_BKA -- (Melihat Persetujuan Disposisi BKA)
    Admin_BKA -- (Menambah SPT BKA)
    Admin_BKA -- (Melihat SPT BKA)
    Admin_BKA -- (Mengajukan SPT BKA)
    Admin_BKA -- (Mencari Surat BKA)
    Admin_BKA -- (Mencari SPT BKA)
    Admin_BKA -- (Melihat Pemberitahuan Surat BKA)
    Admin_BKA -- (Melihat Pemberitahuan SPT BKA)

    
    (Melihat Dashboard)..> (Login) : include
    (Melihat Profil)..> (Login) : include
    (Mengubah Profil)..> (Login) : include
    (Mengubah Password)..> (Login) : include
    (Forgot Password)..> (Login) : include
    (Melihat Role)..> (Login) : include
    (Menambah Role)..> (Melihat Role) : include
    (Mengubah Role)..> (Melihat Role) : include
    (Menghapus Role)..> (Melihat Role) : include
    (Menambah Akses)..> (Melihat Role) : include
    (Mengurangi Akses)..> (Melihat Role) : include

    (Melihat Surat BKA)..> (Login) : include
    (Melihat Persetujuan Disposisi BKA)..> (Melihat Surat BKA) : include
    (Menambah SPT BKA)..> (Melihat SPT BKA) : include
    (Melihat SPT BKA)..> (Login) : include
    (Mengajukan SPT BKA)..> (Melihat SPT BKA) : include
    (Mencari Surat BKA)..> (Melihat Surat BKA) : include
    (Mencari SPT BKA)..> (Melihat SPT BKA) : include
    (Melihat Pemberitahuan Surat BKA)..> (Melihat Surat BKA) : include
    (Melihat Pemberitahuan SPT BKA)..> (Melihat SPT BKA) : include

}

@enduml