@startuml UsecaseMSPT
Left to Right Direction
skinParam packageStyle rectangle

actor Admin

rectangle "Use Case Diagram Manajemen Surat Perintah Tugas"{

    Admin -- (Melihat Dashboard)
    Admin-- (Melihat Profil)
    Admin-- (Mengubah Profil)
    Admin-- (Mengubah Password)
    Admin-- (Forgot Password)
    Admin-- (Melihat Role)
    Admin-- (Menambah Role)
    Admin-- (Mengubah Role)
    Admin-- (Menghapus Role)
    Admin-- (Menambah Akses)
    Admin-- (Mengurangi Akses)
    Admin-- (Melihat Menu)
    Admin-- (Menambah Menu)
    Admin-- (Mengubah Menu)
    Admin-- (Menghapus Menu)
    Admin-- (Melihat Submenu)
    Admin-- (Menambah Submenu)
    Admin-- (Mengubah Submenu)
    Admin-- (Menghapus Submenu)
    Admin-- (Melihat Pegawai TU)
    Admin-- (Menambah Pegawai TU)
    Admin-- (Mengubah Pegawai TU)
    Admin-- (Menghapus Pegawai TU)
    Admin-- (Melihat Pegawai BKD)
    Admin-- (Menambah Pegawai BKD)
    Admin-- (Mengubah Pegawai BKD)
    Admin-- (Menghapus Pegawai BKD)
    Admin-- (Melihat Pegawai BKA)
    Admin-- (Menambah Pegawai BKA)
    Admin-- (Mengubah Pegawai BKA)
    Admin-- (Menghapus Pegawai BKA)
    Admin-- (Melihat Pegawai Trash)
    Admin-- (Megembalikan Pegawai)
    Admin-- (Menghapus Permanen Pegawai)
    Admin-- (Mencari Menu)
    Admin-- (Mencari Submenu)
    Admin-- (Mencari Pegawai TU)
    Admin-- (Mencari Pegawai BKD)
    Admin-- (Mencari Pegawai BKA)
    Admin-- (Mencari Pegawai Trash)

    
(Melihat Dashboard)..> (Login) : include
(Melihat Profil)..> (Login) : include
(Mengubah Profil)..> (Login) : include
(Mengubah Password)..> (Login) : include
(Forgot Password)..> (Login) : include
(Melihat Role)..> (Login) : include
(Menambah Role)..> (Melihat Role) : include
(Mengubah Role)..> (Melihat Role) : include
(Menghapus Role)..> (Melihat Role) : include
(Menambah Akses)..> (Melihat Role) : include
(Mengurangi Akses)..> (Melihat Role) : include

(Melihat Menu)..> (Login) : include
(Menambah Menu)..> (Melihat Menu) : include
(Mengubah Menu)..> (Melihat Menu) : include
(Menghapus Menu)..> (Melihat Menu) : include
(Melihat Submenu)..> (Login) : include
(Menambah Submenu)..> (Melihat Submenu) : include
(Mengubah Submenu)..> (Melihat Submenu) : include
(Menghapus Submenu)..> (Melihat Submenu) : include
(Melihat Pegawai TU)..> (Login) : include
(Menambah Pegawai TU)..> (Melihat Pegawai TU) : include
(Mengubah Pegawai TU)..> (Melihat Pegawai TU) : include
(Menghapus Pegawai TU)..> (Melihat Pegawai TU) : include
(Melihat Pegawai BKD)..> (Login) : include
(Menambah Pegawai BKD)..> (Melihat Pegawai BKD) : include
(Mengubah Pegawai BKD)..> (Melihat Pegawai BKD) : include
(Menghapus Pegawai BKD)..> (Melihat Pegawai BKD) : include
(Melihat Pegawai BKA)..> (Login) : include
(Menambah Pegawai BKA)..> (Melihat Pegawai BKA) : include
(Mengubah Pegawai BKA)..> (Melihat Pegawai BKA) : include
(Menghapus Pegawai BKA)..> (Melihat Pegawai BKA) : include
(Melihat Pegawai Trash)..> (Login) : include
(Megembalikan Pegawai)..> (Melihat Pegawai Trash) : include
(Menghapus Permanen Pegawai)..> (Melihat Pegawai Trash) : include
(Mencari Menu)..> (Melihat Menu) : include
(Mencari Submenu)..> (Melihat Submenu) : include
(Mencari Pegawai TU)..> (Melihat Pegawai TU) : include
(Mencari Pegawai BKD)..> (Melihat Pegawai BKD) : include
(Mencari Pegawai BKA)..> (Melihat Pegawai BKA) : include
(Mencari Pegawai Trash)..> (Melihat Pegawai Trash) : include


}

@enduml