@startuml

autonumber
hide footbox
title Menambah Menu

Actor Administrator
boundary Dashboard_V
boundary Menu_V
boundary AddMenu_V
control Admin_C
control Menu_C
Entity Menu_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Administrator: Halaman Dashboard
Administrator --> Dashboard_V: klik Menu Menu management
Dashboard_V --> Menu_C: index()
Menu_C --> Menu_E:
    
    Menu_E --> Menu_C:
    Menu_C --> Menu_V: load->view()
    Menu_V --> Administrator: Halaman Menu management

Administrator --> Menu_V: klik tombol AddMenu
Menu_V --> Menu_C: AddMenu()
Menu_C --> AddMenu_V: load->view()
AddMenu_V --> Administrator: Halaman AddMenu

Administrator --> AddMenu_V: Mengisi Inputan dan klik tombol add
    note right of Administrator
        Inputan Menu
            end note
AddMenu_V --> Menu_C: AddMenu()
Menu_C --> Menu_E:

alt isValid() case
    
    Menu_E --> Menu_C: isValid()
    Menu_C --> Menu_V: load->view()
    Menu_V --> Administrator: Halaman Menu

else isInvalid() case
    
    Menu_E --> Menu_C: isInValid()
    Menu_C --> AddMenu_V: load->view()
    AddMenu_V --> Administrator: Halaman Add Menu

end
@enduml