@startuml

autonumber
hide footbox
title Menambah Role

Actor Administrator
boundary Dashboard_V
boundary Role_V
boundary AddRole_V
control Admin_C
Entity Role_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Administrator: Halaman Dashboard
Administrator --> Dashboard_V: klik menu Role
Dashboard_V --> Admin_C: Role()
Admin_C --> Role_E:
    
    Role_E --> Admin_C:
    Admin_C --> Role_V: load->view()
    Role_V --> Administrator: Halaman Role

Administrator --> Role_V: klik tombol AddRole
Role_V --> Admin_C: AddRole()
Admin_C --> AddRole_V: load->view()
AddRole_V --> Administrator: Halaman AddRole

Administrator --> AddRole_V: Mengisi Inputan dan klik tombol add
    note right of Administrator
        Inputan Role
            end note
AddRole_V --> Admin_C: AddRole()
Admin_C --> Role_E:

alt isValid() case
    
    Role_E --> Admin_C: isValid()
    Admin_C --> Role_V: load->view()
    Role_V --> Administrator: Halaman Role

else isInvalid() case
    
    Role_E --> Admin_C: isInvalid()
    Admin_C --> AddRole_V: load->view()
    AddRole_V --> Administrator: Halaman Add Role
end


@enduml