@startuml

autonumber
hide footbox
title Mengembalikan Pegawai

Actor Administrator
boundary Dashboard_V
boundary Trash_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Administrator: Halaman Dashboard
Administrator --> Dashboard_V: klik menu Trash Pegawai
Dashboard_V --> Pegawai_C: trash()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> Trash_V: load->view()
    Trash_V --> Administrator: Halaman Trash Pegawai

Administrator --> Trash_V: klik tombol Restore Pegawai
Trash_V --> Pegawai_C: restorepegawai()
Pegawai_C --> Pegawai_E:
   
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> Trash_V: load->view()
    Trash_V --> Administrator: Halaman Trash pegawai

@enduml