@startuml

autonumber
hide footbox
title Melihat Pegawai TU

Actor Administrator
boundary Dashborad_V
boundary PegawaiTU_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Administrator: Halaman Dashborad
Administrator --> Dashborad_V: klik Menu Pegawai TU
Dashborad_V --> Pegawai_C: index()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Administrator: Halaman Pegawai TU

@enduml