@startuml

autonumber
hide footbox
title Mencari Submenu

Actor Administrator
boundary Dashborad_V
boundary Submenu_V
control Admin_C
control Menu_C
Entity Submenu_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Administrator: Halaman Dashborad
Administrator --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> Menu_C: searchsubmenu()
Menu_C --> Submenu_E:
    
    Submenu_E --> Menu_C:
    Menu_C --> Submenu_V: load->view()
    Submenu_V --> Administrator: Halaman Menu management

@enduml