@startuml

autonumber
hide footbox
title Melihat Surat BKD 

Actor AdminBKD
boundary Dashboard_V
boundary SuratBKD_V
control Admin_C
control BKD_C
Entity SuratDisposisi_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdminBKD: Halaman Dashboard
AdminBKD --> Dashboard_V: klik menu Surat BKD 
Dashboard_V --> BKD_C: index()
BKD_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> BKD_C:
    BKD_C --> SuratBKD_V: load->view()
    SuratBKD_V --> AdminBKD: Halaman Surat BKD 

@enduml