@startuml

autonumber
hide footbox
title Melihat SPT BKD 

Actor AdminBKD
boundary Dashboard_V
boundary SPT_V
control Admin_C
control BKD_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdminBKD: Halaman Dashboard
AdminBKD --> Dashboard_V: klik menu Surat Perintah Tugas 
Dashboard_V --> BKD_C: spt()
BKD_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> BKD_C:
    BKD_C --> SPT_V: load->view()
    SPT_V --> AdminBKD: Halaman Surat Perintah Tugas 

@enduml