@startuml

autonumber
hide footbox
title EditProfile Aktor

Actor Aktor
boundary Dashboard_V
boundary EditProfile_V
boundary MyProfile_V
control User_C
Entity User_E

User_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor: Halaman Dashboard_V
Aktor --> Dashboard_V: klik menu EditProfile_V
Dashboard_V --> User_C: edit()
User_C --> User_E:
    
    User_E --> User_C:
    User_C --> EditProfile_V: load->view()
    EditProfile_V --> Aktor: Halaman edit profil

Aktor --> EditProfile_V: Mengisi Inputan
    note right of Aktor
        Inputan fullname dan picture
            end note
EditProfile_V --> User_C: edit()
User_C --> User_E:

alt isValid() case
    
    User_E --> User_C: isValid()
    User_C --> MyProfile_V: load->view()
    MyProfile_V --> Aktor: Halaman MyProfile_V

else isInvalid() case
    
    User_E --> User_C: isInvalid()
    User_C --> EditProfile_V: load->view()
    EditProfile_V --> Aktor: this field is required
end

@enduml