@startuml

autonumber
hide footbox
title Menghapus Surat Masuk

Actor AdminTU
boundary Dashboard_V
boundary SuratMasuk_V
control Admin_C
control SuratMasuk_C
Entity SuratMasuk_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdminTU: Halaman Dashboard
AdminTU --> Dashboard_V: klik menu Surat Masuk
Dashboard_V --> SuratMasuk_C: index()
SuratMasuk_C --> SuratMasuk_E:
    
    SuratMasuk_E --> SuratMasuk_C:
    SuratMasuk_C --> SuratMasuk_V: load->view()
    SuratMasuk_V --> AdminTU: Halaman Surat Masuk

AdminTU --> SuratMasuk_V: klik tombol Delete Surat Masuk
SuratMasuk_V --> SuratMasuk_C: deletepegawaitu()
SuratMasuk_C --> SuratMasuk_E:
   
    SuratMasuk_E --> SuratMasuk_C:
    SuratMasuk_C --> SuratMasuk_V: load->view()
    SuratMasuk_V --> AdminTU: Halaman Surat Masuk

@enduml