@startuml

autonumber
hide footbox
title Memverifikasi SPT BKA

Actor AdminTU
boundary Dashboard_V
boundary KontrolSPTBKA_V
control Admin_C
control KontroSPT_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdminTU: Halaman Dashboard
AdminTU --> Dashboard_V: klik menu SPT BKA
Dashboard_V --> KontroSPT_C: kontrolsptbka()
KontroSPT_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> KontroSPT_C:
    KontroSPT_C --> KontrolSPTBKA_V: load->view()
    KontrolSPTBKA_V --> AdminTU: Halaman SPT BKA

AdminTU --> KontrolSPTBKA_V: klik tombol Accept SPT BKA
KontrolSPTBKA_V --> KontroSPT_C: acceptsptbkalengkap()
KontroSPT_C --> SuratPerintahTugas_E:
   
    SuratPerintahTugas_E --> KontroSPT_C:
    KontroSPT_C --> KontrolSPTBKA_V: load->view()
    KontrolSPTBKA_V --> AdminTU: Halaman SPT BKA

@enduml