@startuml

autonumber
hide footbox
title Melihat Surat Masuk

Actor AdminTU
boundary Dashborad_V
boundary SuratMasuk_V
control Admin_C
control SuratMasuk_C
Entity SuratMasuk_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> AdminTU: Halaman Dashborad
AdminTU --> Dashborad_V: klik Menu Surat Masuk
Dashborad_V --> SuratMasuk_C: index()
SuratMasuk_C --> SuratMasuk_E:
    
    SuratMasuk_E --> SuratMasuk_C:
    SuratMasuk_C --> SuratMasuk_V: load->view()
    SuratMasuk_V --> AdminTU: Halaman Surat Masuk

@enduml