@startuml

autonumber
hide footbox
title Mencari Surat Disposisi BKD

Actor Kepala
boundary Dashborad_V
boundary DisposisiBKD_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Kepala: Halaman Dashborad
Kepala --> Dashborad_V: tulis keyword yang ingin dicari pada form pencarian
Dashborad_V --> SuratDisposisi_C: searchdisposisibkd()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKD_V: load->view()
    DisposisiBKD_V --> Kepala: Halaman Surat Disposisi BKD

@enduml