@startuml

autonumber
hide footbox
title Login Aktor

Actor Aktor
boundary Login_V
boundary Dashboard_V
control Auth_C
Entity User_E

Auth_C --> Login_V: load->view()
Login_V --> Aktor: Halaman Login
Aktor --> Login_V: Mengisi Inputan
    note right of Aktor
        Inputan email dan password
            end note
Login_V --> Auth_C: index()
Auth_C --> User_E: Login()

alt isValid() case
    
    User_E --> Auth_C: isValid()
    Auth_C --> Dashboard_V: load->view()
    Dashboard_V --> Aktor: Halaman Dashboard

else isInvalid() case
    
    User_E --> Auth_C: isInvalid()
    Auth_C --> Login_V: load->view()
    Login_V --> Aktor: email not registered/ wrong password

end

@enduml