@startuml

autonumber
hide footbox
title Tambah Pegawai TU

Actor Aktor_Admin
boundary Dashboard_V
boundary PegawaiTU_V
boundary AddPegawaiTU_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Admin: Halaman Dashboard
Aktor_Admin --> Dashboard_V: klik menu Pegawai TU
Dashboard_V --> Pegawai_C: index()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Aktor_Admin: Halaman Pegawai TU

Aktor_Admin --> PegawaiTU_V: klik tombol Add Pegawai TU
PegawaiTU_V --> Pegawai_C: addpegawaitu()
Pegawai_C --> AddPegawaiTU_V: load->view()
AddPegawaiTU_V --> Aktor_Admin: Halaman Add Pegawai TU

Aktor_Admin --> AddPegawaiTU_V: Mengisi Inputan dan klik tombol add
    note right of Aktor_Admin
        Inputan Nama, NIP, Jenis Kelamin, tempat lahir, tanggal lahir, alamat dan jabatan
            end note
AddPegawaiTU_V --> Pegawai_C: addpegawaitu()
Pegawai_C --> Pegawai_E:

alt isValid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Aktor_Admin: Halaman Pegawai TU

else isInvalid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> AddPegawaiTU_V: load->view()
    AddPegawaiTU_V --> Aktor_Admin: this field is required

end
@enduml