@startuml

autonumber
hide footbox
title Lihat Menu

Actor Aktor_Admin
boundary dashboard
boundary Submenu
boundary addsubmenu
control Admin
control Menu_C
Entity submenu

Admin --> dashboard: load->view()
dashboard --> Aktor_Admin: Halaman dashboard
Aktor_Admin --> dashboard: klik menu Submenu management
dashboard --> Menu_C: Submenu()
Menu_C --> submenu:
    
    submenu --> Menu_C:
    Menu_C --> Submenu: load->view()
    Submenu --> Aktor_Admin: Halaman Submenu management

Aktor_Admin --> Submenu: klik tombol addsubmenu
Submenu --> Menu_C: addsubmenu()
Menu_C --> addsubmenu: load->view()
addsubmenu --> Aktor_Admin: Halaman addsubmenu

Aktor_Admin --> addsubmenu: Mengisi Inputan
    note right of Aktor_Admin
        Inputan Submenu
            end note
addsubmenu --> Menu_C: addsubmenu()
Menu_C --> submenu:

alt isValid() case
    
    submenu --> Menu_C: isValid()
    Menu_C --> Submenu: load->view()
    Submenu --> Aktor_Admin: Halaman Submenu

else isInvalid() case
    
    submenu --> Menu_C: isValid()
    Menu_C --> addsubmenu: load->view()
    addsubmenu --> Aktor_Admin: this field is required

end
@enduml