@startuml

autonumber
hide footbox
title Ubah Menu

Actor Aktor_Admin
boundary Dashboard_V
boundary Menu_V
boundary EditMenu_V
control Admin_C
control Menu_C
Entity Menu_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Aktor_Admin: Halaman Dashboard
Aktor_Admin --> Dashboard_V: klik Menu_E Menu management
Dashboard_V --> Menu_C: index()
Menu_C --> Menu_E:
    
    Menu_E --> Menu_C:
    Menu_C --> Menu_V: load->view()
    Menu_V --> Aktor_Admin: Halaman Menu management

Aktor_Admin --> Menu_V: klik tombol EditMenu
Menu_V --> Menu_C: EditMenu()
Menu_C --> EditMenu_V: load->view()
EditMenu_V --> Aktor_Admin: Halaman EditMenu

Aktor_Admin --> EditMenu_V: Mengisi Inputan dan klik tombol edit
    note right of Aktor_Admin
        Inputan Menu
            end note
EditMenu_V --> Menu_C: EditMenu()
Menu_C --> Menu_E:

alt isValid() case
    
    Menu_E --> Menu_C: isValid()
    Menu_C --> Menu_V: load->view()
    Menu_V --> Aktor_Admin: Halaman Menu

else isInvalid() case
    
    Menu_E --> Menu_C: isValid()
    Menu_C --> EditMenu_V: load->view()
    EditMenu_V --> Aktor_Admin: this field is required

end
@enduml