@startuml

autonumber
hide footbox
title Lihat Menu

Actor Aktor_Admin
boundary dashboard
boundary Menu
boundary editmenu
control Admin
control Menu_C
Entity menu

Admin --> dashboard: load->view()
dashboard --> Aktor_Admin: Halaman dashboard
Aktor_Admin --> dashboard: klik menu Menu management
dashboard --> Menu_C: index()
Menu_C --> menu:
    
    menu --> Menu_C:
    Menu_C --> Menu: load->view()
    Menu --> Aktor_Admin: Halaman menu management

Aktor_Admin --> Menu: klik tombol editmenu
Menu --> Menu_C: editmenu()
Menu_C --> editmenu: load->view()
editmenu --> Aktor_Admin: Halaman editmenu

Aktor_Admin --> editmenu: Mengisi Inputan
    note right of Aktor_Admin
        Inputan menu
            end note
editmenu --> Menu_C: editmenu()
Menu_C --> menu:

alt isValid() case
    
    menu --> Menu_C: isValid()
    Menu_C --> Menu: load->view()
    Menu --> Aktor_Admin: Halaman Menu

else isInvalid() case
    
    menu --> Menu_C: isValid()
    Menu_C --> editmenu: load->view()
    editmenu --> Aktor_Admin: this field is required

end
@enduml