@startuml

autonumber
hide footbox
title Lihat Role

Actor Aktor_Admin
boundary Dashvoard_V
boundary Role_V
control Admin_C
Entity Role_E

Admin_C --> Dashvoard_V: load->view()
Dashvoard_V --> Aktor_Admin: Halaman Dashvoard
Aktor_Admin --> Dashvoard_V: klik menu Role
Dashvoard_V --> Admin_C: Role()
Admin_C --> Role_E:
    
    Role_E --> Admin_C:
    Admin_C --> Role_V: load->view()
    Role_V --> Aktor_Admin: Halaman Role

@enduml