@startuml

autonumber
hide footbox
title Pemberitahuan SPT BKD

Actor AdministratorTU
boundary Dashborad_V
boundary SPTBKD_V
control Admin_C
control KontrolSPT_C
Entity SuratPerintahTugas_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> AdministratorTU: Halaman Dashborad
AdministratorTU --> Dashborad_V: klik tombol pemberitahuan
Dashborad_V --> KontrolSPT_C: kontrolsptbka()
KontrolSPT_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> SPTBKD_V: load->view()
    SPTBKD_V --> AdministratorTU: Halaman SPT BKD

@enduml