@startuml Usecase
Left to Right Direction
skinParam packageStyle rectangle

actor Administrator_TU

rectangle "Use Case Diagram Manajemen Surat Perintah Tugas"{

    Administrator_TU -- (Melihat Dashboard)
    Administrator_TU -- (Melihat Profil)
    Administrator_TU -- (Mengubah Profil)
    Administrator_TU-- (Mengubah Password)
    Administrator_TU -- (Forgot Password)
    Administrator_TU -- (Melihat Surat Masuk)
    Administrator_TU -- (Menambah Surat Masuk)
    Administrator_TU -- (Mengubah Surat Masuk)
    Administrator_TU -- (Menghapus Surat Masuk)
    Administrator_TU -- (Melihat File Disposisi)
    Administrator_TU -- (Mendisposisi Surat Masuk)
    Administrator_TU -- (Melihat Trash Surat Masuk)
    Administrator_TU -- (Mengembalikan Surat Masuk)
    Administrator_TU -- (Menghapus Permanen Surat Masuk)
    Administrator_TU -- (Melihat SPT BKD)
    Administrator_TU -- (Melihat File SPT Lengkap BKD)
    Administrator_TU -- (Mengupload SPT Lengkap BKD)
    Administrator_TU -- (Memverifikasi SPT Lengkap BKD)
    Administrator_TU -- (Melihat SPT BKA)
    Administrator_TU -- (Melihat File SPT Lengkap BKA)
    Administrator_TU -- (Mengupload SPT Lengkap BKA)
    Administrator_TU -- (Memverifikasi SPT Lengkap BKA)
    Administrator_TU -- (Mencari Surat Masuk)
    Administrator_TU -- (Mencari Trash Surat Masuk)
    Administrator_TU -- (Mencari SPT BKD)
    Administrator_TU -- (Mencari SPT BKA)
    Administrator_TU -- (Melihat Pemberitahuan Surat Masuk)
    Administrator_TU -- (Melihat Pemberitahuan SPT BKD)
    Administrator_TU -- (Melihat Pemberitahuan SPT BKA)
    
    ' semua aktor
    (Melihat Dashboard)..> (Login) : include
    (Melihat Profil)..> (Login) : include
    (Mengubah Profil)..> (Login) : include
    (Mengubah Password)..> (Login) : include
    (Forgot Password)..> (Login) : include
    (Melihat Role)..> (Login) : include
    (Menambah Role)..> (Melihat Role) : include
    (Mengubah Role)..> (Melihat Role) : include
    (Menghapus Role)..> (Melihat Role) : include
    (Menambah Akses)..> (Melihat Role) : include
    (Mengurangi Akses)..> (Melihat Role) : include

    ' admin tu
   (Melihat Surat Masuk)..> (Login) : include
   (Menambah Surat Masuk)..> (Melihat Surat Masuk) : include
   (Mengubah Surat Masuk)..> (Melihat Surat Masuk) : include
   (Menghapus Surat Masuk)..> (Melihat Surat Masuk) : include
   (Melihat File Disposisi)..> (Melihat Surat Masuk) : include
   (Mendisposisi Surat Masuk)..> (Melihat Surat Masuk) : include
   (Melihat Trash Surat Masuk)..> (Login) : include
   (Mengembalikan Surat Masuk)..> (Melihat Trash Surat Masuk) : include
   (Menghapus Permanen Surat Masuk)..> (Melihat Trash Surat Masuk) : include
   (Melihat SPT BKD)..> (Login) : include
   (Melihat File SPT Lengkap BKD)..> (Melihat SPT BKD) : include
   (Mengupload SPT Lengkap BKD)..> (Melihat SPT BKD) : include
   (Memverifikasi SPT Lengkap BKD)..> (Melihat SPT BKD) : include
   (Melihat SPT BKA)..> (Login) : include
   (Melihat File SPT Lengkap BKA)..> (Melihat SPT BKA) : include
   (Mengupload SPT Lengkap BKA)..> (Melihat SPT BKA) : include
   (Memverifikasi SPT Lengkap BKA)..> (Melihat SPT BKA) : include
   (Mencari Surat Masuk)..> (Melihat Surat Masuk) : include
   (Mencari Trash Surat Masuk)..> (Melihat Trash Surat Masuk) : include
   (Mencari SPT BKD)..> (Melihat SPT BKD) : include
   (Mencari SPT BKA)..> (Melihat SPT BKA) : include
   (Melihat Pemberitahuan Surat Masuk)..> (Melihat Surat Masuk) : include
   (Melihat Pemberitahuan SPT BKD)..> (Melihat SPT BKD) : include
   (Melihat Pemberitahuan SPT BKA)..> (Melihat SPT BKA) : include

}

@enduml