@startuml

autonumber
hide footbox
title Menghapus Permanen Pegawai

Actor Admin
boundary Dashboard_V
boundary Trash_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Admin: Halaman Dashboard
Admin --> Dashboard_V: klik menu Trash Pegawai
Dashboard_V --> Pegawai_C: trash()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> Trash_V: load->view()
    Trash_V --> Admin: Halaman Trash Pegawai

Admin --> Trash_V: klik tombol Delete Permanent Pegawai
Trash_V --> Pegawai_C: deletepermanentpegawai()
Pegawai_C --> Pegawai_E:
   
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> Trash_V: load->view()
    Trash_V --> Admin: Halaman Trash pegawai

@enduml