@startuml

autonumber
hide footbox
title Menghapus Pegawai TU

Actor Admin
boundary Dashboard_V
boundary PegawaiTU_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Admin: Halaman Dashboard
Admin --> Dashboard_V: klik menu Pegawai TU
Dashboard_V --> Pegawai_C: index()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Admin: Halaman Pegawai TU

Admin --> PegawaiTU_V: klik tombol Delete Pegawai TU
PegawaiTU_V --> Pegawai_C: deletepegawaitu()
Pegawai_C --> Pegawai_E:
   
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Admin: Halaman Pegawai TU

@enduml