@startuml

autonumber
hide footbox
title Mengubah Pegawai BKD

Actor Admin
boundary Dashboard_V
boundary PegawaiBKD_V
boundary EditPegawaiBKD_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Admin: Halaman Dashboard
Admin --> Dashboard_V: klik menu Pegawai BKD
Dashboard_V --> Pegawai_C: pegawaibkd()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiBKD_V: load->view()
    PegawaiBKD_V --> Admin: Halaman Pegawai BKD

Admin --> PegawaiBKD_V: klik tombol Edit Pegawai TU
PegawaiBKD_V --> Pegawai_C: editpegawaibkd()
Pegawai_C --> EditPegawaiBKD_V: load->view()
EditPegawaiBKD_V --> Admin: Halaman Edit Pegawai BKD

Admin --> EditPegawaiBKD_V: Mengisi Inputan dan klik tombol Edit
    note right of Admin
        Inputan Nama, NIP, Jenis Kelamin, tempat lahir, tanggal lahir, alamat dan jabatan
            end note
EditPegawaiBKD_V --> Pegawai_C: editpegawaibkd()
Pegawai_C --> Pegawai_E:

alt isValid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> PegawaiBKD_V: load->view()
    PegawaiBKD_V --> Admin: Halaman Pegawai BKD

else isInvalid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> EditPegawaiBKD_V: load->view()
    EditPegawaiBKD_V --> Admin: Halaman Add Pegawai BKD

end
@enduml