@startuml

autonumber
hide footbox
title Mengubah Pegawai TU

Actor Admin
boundary Dashboard_V
boundary PegawaiTU_V
boundary EditPegawaiTU_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Admin: Halaman Dashboard
Admin --> Dashboard_V: klik menu Pegawai TU
Dashboard_V --> Pegawai_C: index()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Admin: Halaman Pegawai TU

Admin --> PegawaiTU_V: klik tombol Edit Pegawai TU
PegawaiTU_V --> Pegawai_C: editpegawaitu()
Pegawai_C --> EditPegawaiTU_V: load->view()
EditPegawaiTU_V --> Admin: Halaman Edit Pegawai TU

Admin --> EditPegawaiTU_V: Mengisi Inputan dan klik tombol Edit
    note right of Admin
        Inputan Nama, NIP, Jenis Kelamin, tempat lahir, tanggal lahir, alamat dan jabatan
            end note
EditPegawaiTU_V --> Pegawai_C: editpegawaitu()
Pegawai_C --> Pegawai_E:

alt isValid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> PegawaiTU_V: load->view()
    PegawaiTU_V --> Admin: Halaman Pegawai TU

else isInvalid() case
    
    Pegawai_E --> Pegawai_C: isValid()
    Pegawai_C --> EditPegawaiTU_V: load->view()
    EditPegawaiTU_V --> Admin: Halaman Add Pegawai TU

end
@enduml