@startuml

autonumber
hide footbox
title Lihat Pegawai BKA

Actor Aktor_Admin
boundary Dashborad_V
boundary PegawaiBKA_V
control Admin_C
control Pegawai_C
Entity Pegawai_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Aktor_Admin: Halaman Dashborad
Aktor_Admin --> Dashborad_V: klik Menu Pegawai BKA
Dashborad_V --> Pegawai_C: pegawaibka()
Pegawai_C --> Pegawai_E:
    
    Pegawai_E --> Pegawai_C:
    Pegawai_C --> PegawaiBKA_V: load->view()
    PegawaiBKA_V --> Aktor_Admin: Halaman Pegawai BKA

@enduml