@startuml

autonumber
hide footbox
title Melihat Submenu

Actor Admin
boundary Dashboard_V
boundary Submenu_V
control Admin_C
control Menu_C
Entity Submenu_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> Admin: Halaman Dashboard
Admin --> Dashboard_V: klik Submenu submenu management
Dashboard_V --> Menu_C: Submenu()
Menu_C --> Submenu_E:
    
    Submenu_E --> Menu_C:
    Menu_C --> Submenu_V: load->view()
    Submenu_V --> Admin: Halaman Submenu management

@enduml