@startuml

autonumber
hide footbox
title Melihat File SPT BKA

Actor AdministratorTU
boundary Dashboard_V
boundary KontrolSPTBKA_V
boundary PDF_V
control Admin_C
control KontrolSPT_C
Entity SuratPerintahTugas_E

Admin_C --> Dashboard_V: load->view()
Dashboard_V --> AdministratorTU: Halaman Dashboard
AdministratorTU --> Dashboard_V: klik menu SPT BKA
Dashboard_V --> KontrolSPT_C: kontrolsptbka()
KontrolSPT_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> KontrolSPTBKA_V: load->view()
    KontrolSPTBKA_V --> AdministratorTU: Halaman SPT BKA

AdministratorTU --> KontrolSPTBKA_V: klik tombol Lihat File SPT BKA
KontrolSPTBKA_V --> KontrolSPT_C: viewspt()
KontrolSPT_C --> SuratPerintahTugas_E:
   
    SuratPerintahTugas_E --> KontrolSPT_C:
    KontrolSPT_C --> PDF_V: load->view()
    PDF_V --> AdministratorTU: Tampilan file SPT

@enduml