@startuml

autonumber
hide footbox
title Melihat Trash Surat Masuk

Actor AdministratorTU
boundary Dashborad_V
boundary Trash_V
control Admin_C
control SuratMasuk_C
Entity SuratMasuk_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> AdministratorTU: Halaman Dashborad
AdministratorTU --> Dashborad_V: klik Menu Trash Surat Masuk
Dashborad_V --> SuratMasuk_C: trash()
SuratMasuk_C --> SuratMasuk_E:
    
    SuratMasuk_E --> SuratMasuk_C:
    SuratMasuk_C --> Trash_V: load->view()
    Trash_V --> AdministratorTU: Halaman Trash Surat Masuk

@enduml