@startuml

autonumber
hide footbox
title Pemberitahuan Persetujuan Surat SPT BKA

Actor Aktor_Kepala
boundary Dashborad_V
boundary PersetujuanSPTBKA_V
control Admin_C
control SuratPerintahTugas_C
Entity SuratPerintahTugas_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Aktor_Kepala: Halaman Dashborad
Aktor_Kepala --> Dashborad_V: klik tombol pemberitahuan
Dashborad_V --> SuratPerintahTugas_C: sptbka()
SuratPerintahTugas_C --> SuratPerintahTugas_E:
    
    SuratPerintahTugas_E --> SuratPerintahTugas_C:
    SuratPerintahTugas_C --> PersetujuanSPTBKA_V: load->view()
    PersetujuanSPTBKA_V --> Aktor_Kepala: Halaman Persetujuan Surat SPT BKA

@enduml