@startuml

autonumber
hide footbox
title Pemberitahuan Surat Disposisi BKA

Actor Kepala
boundary Dashborad_V
boundary DisposisiBKA_V
control Admin_C
control SuratDisposisi_C
Entity SuratDisposisi_E

Admin_C --> Dashborad_V: load->view()
Dashborad_V --> Kepala: Halaman Dashborad
Kepala --> Dashborad_V: klik tombol pemberitahuan
Dashborad_V --> SuratDisposisi_C: disposisibka()
SuratDisposisi_C --> SuratDisposisi_E:
    
    SuratDisposisi_E --> SuratDisposisi_C:
    SuratDisposisi_C --> DisposisiBKA_V: load->view()
    DisposisiBKA_V --> Kepala: Halaman Surat Disposisi BKA

@enduml